"""Initial migration

Revision ID: 50385a88da66
Revises: 
Create Date: 2026-04-02 23:40:16.264584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50385a88da66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_tenant_snapshot_date')
    )
    op.create_table('department_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('total_gifts', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('goal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pct_to_goal', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_gift', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_expectancies', sa.Integer(), nullable=True),
    sa.Column('open_estates', sa.Integer(), nullable=True),
    sa.Column('recorded_expectancies', sa.Integer(), nullable=True),
    sa.Column('third_party_total_gifts', sa.Integer(), nullable=True),
    sa.Column('third_party_total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('third_party_goal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('third_party_pct_to_goal', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fund_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pct_of_total', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('onetime_count', sa.Integer(), nullable=True),
    sa.Column('recurring_count', sa.Integer(), nullable=True),
    sa.Column('online_count', sa.Integer(), nullable=True),
    sa.Column('mailed_in_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_type_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('gift_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('pct_of_gifts', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('primary_addressee', sa.String(length=255), nullable=True),
    sa.Column('appeal_id', sa.String(length=255), nullable=True),
    sa.Column('split_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fund_description', sa.String(length=255), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('gift_type', sa.String(length=100), nullable=True),
    sa.Column('gift_reference', sa.String(length=255), nullable=True),
    sa.Column('gift_date', sa.Date(), nullable=True),
    sa.Column('extra_field', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('pct_of_gifts', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_breakdowns')
    op.drop_table('raw_gifts')
    op.drop_table('gift_type_breakdowns')
    op.drop_table('fund_breakdowns')
    op.drop_table('department_summaries')
    op.drop_table('snapshots')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
